### ISSUE TITLE
No errors, but no rows created

### ISSUE THREAD

**Issue by shedd** [Fivell/active_admin_import#18]
This gem looks great, but when I tried to use it, no data got imported.

I tried everything I could think of - I used the before/after import procs to confirm that it was running.  Tried multiple options, turning validation off, setting permit_params.  I used the before_import proc to confirm that the file was getting uploaded and the file was readable on the server.

Not sure - maybe this just doesn't work with the latest master branch version of ActiveAdmin?

**Comment by Fivell** [comment]
@shedd , please try branch 3.0.0, if you can. Now I'm refactoring and writing specs for this gem.
