### ISSUE TITLE
Error: undefined method `underscore' for nil:NilClass

### ISSUE THREAD

**Issue by jackjackattack23** [Fivell/active_admin_import#40]
I'm having issues getting files to import.  What format should the csv be in for the default import to work?

using:  active_admin_import  in resource file

I keep getting this error on import "Error: undefined method `underscore' for nil:NilClass."  I tried another file but then I get "You can't import empty file."

File one:
1,Credit,325,,,,,,Approved,CPD,,,

File two:
"school_id","trans_type","points","payment","attendee","event_start","event_end","course","approved","points_type","trans_date","approver_comments"
"1","Credit","250","","","","","","Approved","CPD","",

I tried adding in the quotes to see if that would make a difference.

Here is the table schema:

create_table "points_transactions", force: :cascade do |t|
    t.integer  "school_id"
    t.string   "trans_type"
    t.integer  "points"
    t.integer  "payment"
    t.string   "attendee"
    t.date     "event_start"
    t.date     "event_end"
    t.string   "course"
    t.string   "approved"
    t.string   "points_type"
    t.string   "trans_date"
    t.datetime "created_at",        null: false
    t.datetime "updated_at",        null: false
    t.string   "approver_comments"
  end

Any help you can give would be great!

**Comment by jackjackattack23** [comment]
Do I need to include fields that should be automatically created?  i.e. id, create_at, update_at

**Comment by jackjackattack23** [comment]
I messed with it some more and finally got this to work:

active_admin_import :validate => true,
            :template_object => ActiveAdminImport::Model.new(
                #:hint => "file will be imported with such header format: 'body','title','author'",
                :csv_headers => ["school_id", "trans_type", "points", "payment", "attendee", "event_start", "event_end", "course", "approved", "points_type", "trans_date", "approver_comments"] 
            )

**Comment by Fivell** [comment]
@jackjackattack23, sorry for late response. Did specifying of ```csv_headers``` resolve your problem ?

**Comment by jackjackattack23** [comment]
Yes, using the code I posted directly above worked great.
